#!/usr/bin/env bash
# Bash script that
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
echo $$ > /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
